---
deployment:
  tasks:
    - export DEPLOYPATH=/home/youthhub/youthconnect.org.bd/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp team.html $DEPLOYPATH
    - /bin/cp donation.html $DEPLOYPATH
    - /bin/cp volunteer.html $DEPLOYPATH
    - /bin/cp partner.html $DEPLOYPATH
    - /bin/cp privacy-policy.html $DEPLOYPATH
