---
deployment:
  tasks:
    - export DEPLOYPATH=/home/youthhub/youthconnect.org.bd/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp team.html $DEPLOYPATH
    - /bin/cp get-involved.html $DEPLOYPATH
    - /bin/cp donation.html $DEPLOYPATH
    - /bin/cp volunteer.html $DEPLOYPATH
    - /bin/cp partner.html $DEPLOYPATH
    - /bin/cp privacy-policy.html $DEPLOYPATH
    - /bin/cp events.html $DEPLOYPATH
    - /bin/cp events-config.js $DEPLOYPATH
    - /bin/cp events-page.js $DEPLOYPATH
    - /bin/cp events.js $DEPLOYPATH
    - /usr/bin/perl -0pi -e 's#<div class="footer-right">.*?</div>#<div class="footer-right"><a href="privacy-policy.html">Privacy Policy</a></div>#gs' $DEPLOYPATH/*.html
