---
deployment:
  tasks:
    - export DEPLOYPATH=/home/youthhub/youthconnect.org.bd/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp team.html $DEPLOYPATH
    - /bin/cp get-involved.html $DEPLOYPATH
    - /bin/cp donation.html $DEPLOYPATH
    - /bin/cp volunteer.html $DEPLOYPATH
    - /bin/cp partner.html $DEPLOYPATH
    - /bin/cp privacy-policy.html $DEPLOYPATH
    - /bin/cp events.html $DEPLOYPATH
    - /bin/cp events-config.js $DEPLOYPATH
    - /bin/cp events-page.js $DEPLOYPATH
    - /bin/cp events.js $DEPLOYPATH
    - /bin/cp campaigns.html $DEPLOYPATH
    - /bin/cp campaign-menstrual-health.html $DEPLOYPATH
    - /bin/cp clean-page.js $DEPLOYPATH
    - /bin/cp -R team $DEPLOYPATH
    - /bin/cp -R events $DEPLOYPATH
    - /bin/cp -R campaigns $DEPLOYPATH
    - /bin/cp -R campaign-menstrual-health $DEPLOYPATH
    - /bin/cp -R get-involved $DEPLOYPATH
    - /bin/cp -R donation $DEPLOYPATH
    - /bin/cp -R volunteer $DEPLOYPATH
    - /bin/cp -R partner $DEPLOYPATH
    - /bin/cp -R privacy-policy $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
